# Generated by Django 3.2.5 on 2022-06-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreManager', '0005_auto_20220616_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ScoreManager.person'),
        ),
    ]
