# Generated by Django 3.2.5 on 2022-06-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreManager', '0006_team_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='point',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ScoreManager.team'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('max_point', models.IntegerField(null=True)),
                ('type', models.IntegerField(null=True)),
                ('attendance', models.ManyToManyField(to='ScoreManager.Person')),
            ],
        ),
    ]
