# Generated by Django 3.2.5 on 2022-06-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreManager', '0008_alter_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
