# Generated by Django 3.2.5 on 2022-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreManager', '0010_auto_20220706_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
