# Generated by Django 3.2.5 on 2022-07-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreManager', '0011_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
