# Generated by Django 3.2.5 on 2022-07-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ScoreManager', '0012_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ScoreManager.event')),
                ('subject', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ScoreManager.event',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ScoreManager.event')),
                ('test', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ScoreManager.event',),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='event',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_scoremanager.event_set+', to='contenttypes.contenttype'),
        ),
    ]
