# Generated by Django 3.2.5 on 2022-07-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreManager', '0013_auto_20220710_2248'),
    ]

    operations = [
    ]
