# Generated by Django 3.2.5 on 2022-07-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreManager', '0014_auto_20220710_2250'),
    ]

    operations = [
    ]
